language: python
python:
  - "3.4"

install:
  - "make install_dependencies"

services:
  - redis-server

branches:
  only:
    - master

script: make test

notifications:
  email:
    on_success: never
    on_failure: always
